// <auto-generated />
namespace Donut_Shop_App.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedClientDonut : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedClientDonut));
        
        string IMigrationMetadata.Id
        {
            get { return "202107011317119_addedClientDonut"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
